### ISSUE TITLE
Build-keretrendszer-beüzemelése-(Maven) + CI

### ISSUE THREAD

**Issue by LenkovicsAkos** [BME-MIT-IET/iet-hf-2023-ieteszt#1]
Még nem létezik a pom.xml fájl amit futtat a maven

**Comment by Martinovics** [comment]
Létrejött a pom fájl, de nem fut le a Java CI with Maven / build (pull_request), mert hiányos.
See: https://github.com/BME-MIT-IET/iet-hf-2023-ieteszt/pull/2#issuecomment-1555876910

**Comment by Martinovics** [comment]
Működik a maven, de egyelőre csak lebuildeli a projektet. Később hozzá lehet adni extra lépéseket a workflows/maven.yaml fájlhoz
See https://github.com/BME-MIT-IET/iet-hf-2023-ieteszt/pull/5#issuecomment-1556161264

**Comment by LenkovicsAkos** [comment]
DONE
